
MODEL_A_NAME="Qwen/Qwen3-8B"
MODEL_B_NAME="Qwen/Qwen3-14B"

# CUDA devices for each model server (e.g. "0,1" or "2,3"). Each process sees these as 0,1,...
MODEL_A_CUDA_VISIBLE_DEVICES="0,1  "
MODEL_B_CUDA_VISIBLE_DEVICES="0,1"

MODEL_A_GPU_MEMORY_UTILIZATION=0.35
MODEL_B_GPU_MEMORY_UTILIZATION=0.54

MODEL_A_TENSOR_PARALLEL_SIZE=2
MODEL_B_TENSOR_PARALLEL_SIZE=2
MODEL_B_PIPELINE_PARALLEL_SIZE=1
MODEL_A_PIPELINE_PARALLEL_SIZE=1

MODEL_A_ACTIVE_THREAD_PERCENTAGE=10
MODEL_B_ACTIVE_THREAD_PERCENTAGE=80

MODEL_A_MAX_LEN=1024
MODEL_B_MAX_LEN=1024

UVICORN_MODEL_A_PORT=8001
UVICORN_MODEL_B_PORT=8002
ROUTER_PORT=8000

ROUTER_BATCH_SIZE=8
ROUTER_BATCH_TIMEOUT_MS=25

# SLO: request is good if TTFT < SLO_TTFT_MS AND p95(TBTs) < SLO_TBT_P95_MS. Goodput = throughput * SLO attainment rate.
SLO_TTFT_MS=500
SLO_TBT_P95_MS=60

# Comma-separated devices for router models (e.g. "cuda:0,cuda:1"). Prompts randomly routed to one.
# With ROUTER_CUDA_VISIBLE_DEVICES, cuda:0 is the first visible GPU, etc.
ROUTER_MODEL_DEVICES="cuda:0,cuda:1"

# Optional: restrict router to specific GPUs (e.g. "2,3" on a node with 4 GPUs)
# ROUTER_CUDA_VISIBLE_DEVICES="2,3"

