
MODEL_A_NAME="Qwen/Qwen3-1.7B"
MODEL_B_NAME="Qwen/Qwen3-1.7B"

MODEL_A_GPU_MEMORY_UTILIZATION=0.4
MODEL_B_GPU_MEMORY_UTILIZATION=0.4

MODEL_A_TENSOR_PARALLEL_SIZE=2
MODEL_B_TENSOR_PARALLEL_SIZE=2

MODEL_A_ACTIVE_THREAD_PERCENTAGE=60
MODEL_B_ACTIVE_THREAD_PERCENTAGE=10

MODEL_A_MAX_LEN=1024
MODEL_B_MAX_LEN=1024

UVICORN_MODEL_A_PORT=8001
UVICORN_MODEL_B_PORT=8002
ROUTER_PORT=8000